### ISSUE TITLE
Disk recovery - updates

### ISSUE THREAD

**Issue by amichair** [timwhite/technicallytim#1]
Thanks for the article, it's been very helpful!

A few updates that might save time for the next person to need it:
- instead of the hex calculations and using bc, one can simply use 'ddrescuelog -l- ddrescue.log'. This outputs all the bad ('-') sector numbers in decimal, i.e. it does both the division by sector size and conversion to decimal, and in addition it outputs all the sectors and not just the first one of each series of bad blocks (you mention this in the last paragraph but with no example of how to do this). So this one command takes care of a lot of stuff in one fell swoop.
- in some larger disks nowadays the sector size is 4096 rather than 512. Thus calculating the 'data unit' used in the sleuthkit tools might require an additional division by 8 (after division by 512).
- the version of sleuthkit in Ubuntu (up to 13.10, and it looks like it won't change by the 14.04 release this week) is a couple years old, and as it turns out, does not support ext4. While this is platform-specific (though pretty common platform), the important note is that blkstat works ok, but then ifind says 'inode not found', which is a bit perplexing considering it is marked as 'Allocated'. So the filesystem auto-detection fails silently. Only if one specifies '-f ext4' explicitly does he find out that ext4 is not supported. I had to download and build the latest sleuthkit myself for it to work with ext4 properly.

Thanks once again for this great tutorial!

**Comment by timwhite** [comment]
Comment updated. Reopen this issue for new comments to http://tim.purewhite.id.au/2011/04/disk-recovery-which-files-are-damaged/

**Comment by filamento** [comment]
This info could be useful for people using Windows:

Microsoft has a freeware tool for NTFS volumes named NFI.exe (located in the OEM Support Tools 3 SR2, released in 2000). Its syntax is a bit convoluted, but here are some examples:

Look for files located in physical sector 9999 (LBA addresses are always in decimal):

nfi.exe \device\harddisk1\Partition0 9999
nfi.exe \Device\Harddisk0\DR0 9999

Newer versions of Windows can use a different syntax to identify hard disks, so you can tell which one you need by using these commands:

wmic.exe path Win32_DiskDrive get DeviceID,PNPDeviceID
wmic.exe path Win32_PnPSignedDriver where "DeviceName like '%dis%'" get DeviceID,PDO

And, as an alternative, there's also a shareware tool called DiskExplorer from Runtime Software, which works for both FAT and NTFS volumes. It has a GUI, so it's somewhat easier to use.

Kind Regards.
